import React from 'react';
import RoundButton from '../../../buttons/RoundButton';
import { ButtonTypes } from '../../../../utils/helpers';

export default function Section1(): JSX.Element {
    return (
        <div className='w-full flex justify-center items-center mt-[40px] mb-[227px]' id="home">
            <div>
                <div className='w-[72px] h-[10px] bg-[#3683FC] mb-[48px]'></div>
                <div className='text-[48px] font-semibold mb-[31px]'>
                    Your Data can <span className='text-[#3683FC]'>Cure You</span>
                </div>
                <div className='max-w-[650px] text-[26px] mb-[64px]'>
                    Early stages prediction & prevention of severe diseases that can significantly extend your health span.
                    <br></br>
                    Powered by AI and Computer Vision, verified by scientists, generated by Big Data from clinical trials.
                </div>
                <RoundButton content='Download App' shape={ButtonTypes.secondary}></RoundButton>
            </div>
            <img src='dashboard/images/Group 4604.png' alt='phone' className='max-w-[904px] max-h-[678px] w-1/2'></img>
        </div>
    )
}